### ISSUE TITLE
Use GNotification instead of libnotify

### ISSUE THREAD

**Issue by elboulangero** [nicklan/pnmixer#103]
See this page: <https://developer.gnome.org/GNotification>

I'd like to give it a try when I have some time. Then we could drop the `libnotify` dependency, and there would be no need to make notifications optional since it's built-in in `GLib`.

**Comment by hasufell** [comment]
I've done that in a local branch. It doesn't look like a good idea to me, because there are several problems:
* `notify_notification_set_hint` allowed the notify system to show a "progress bar" for the volume level... this function is gone now, so we only have textual representation
* showing icons doesn't seem to work at all, also see http://stackoverflow.com/questions/27341087/glib-gnotification-doesnt-show-icon
* `notify_notification_set_timeout` is gone, so we are going to break https://github.com/nicklan/pnmixer/commit/21db2057590f1c85c1c02b1dd9c64f65ce7de251

**Comment by hasufell** [comment]
https://github.com/hasufell/pnmixer/commit/44a22feb0e8ca89c70e1aaa971f10545b35dadaa

**Comment by elboulangero** [comment]
I didn't have time to look at that yet. I think I will have time in a few weeks. Please keep your branch alive until then :smile:

**Comment by elboulangero** [comment]
Hey I had a quick look, indeed I agree with you.

At first I though that GNotification was roughly like "libnotify merged into GLib". But not really. It seems that it addresses different need.

One of the main advantages of GNotification is the persistence of notifications. But for PNMixer, we don't want that.

Also, when reading about it on [GNotification HowdoI](https://developer.gnome.org/GNotification/), I have a strange feeling. It looks like a "gnome-oriented" feature, which makes me wary.

So, yeah, let's stick with libnotify. It does the job.
