### ISSUE TITLE
when preferences window is open, left-click on tray icon doesn't seem to work

### ISSUE THREAD

**Issue by hasufell** [nicklan/pnmixer#141]

**Comment by elboulangero** [comment]
Is it really needed ? I introduced this behavior in bbba2b74305af080f1eec07bf19d8d1c65e00942.

If the comment is not clear, feel free to revert this commit and try by yourself, you will see quickly what  the problem is. Then feel free to make a better comment :) (I hardly understand my own comments after a while, I think I'm not very good at commenting in English).

**Comment by hasufell** [comment]
Well, but it worked fine in `v0.6.1`, so this is a regression. Unfortunately I haven't enough time to look at the callback code.

**Comment by elboulangero** [comment]
Fixed in 16e96fac2477fb679e48dcc3ee7f14a1fb385d8b

**Comment by hasufell** [comment]
that works :+1:
