### ISSUE TITLE
allow to close Prefs dialogue with ESC

### ISSUE THREAD

**Issue by landroni** [nicklan/pnmixer#91]
Another trivial request. It's very often that Prefs dialogues can be closed with ESC. For keyboard-addicted types, this is a life changer... :)

**Comment by elboulangero** [comment]
Sounds good to me

**Comment by hasufell** [comment]
check that commit out, it also supports to hit Enter

**Comment by landroni** [comment]
Looks great to me!

**Comment by hasufell** [comment]
nope, this breaks some stuff

**Comment by hasufell** [comment]
The proper way would be to make it a GtkDialog, then we get that stuff for free. But it caused more trouble for me.

**Comment by hasufell** [comment]
The latest one looks better: ef20557e711926afc56008b70d987b1a0556c3c7

**Comment by hasufell** [comment]
oops, I accidentially merged this... I am getting confused with the feature branches^^

**Comment by hasufell** [comment]
should I revert or does this look ok @elboulangero

**Comment by elboulangero** [comment]
It looks OK, but I'm a Gtk newbie to be honest :) @landroni is the keyboard-shortcut guy, if there's something wrong he will notice.

**Comment by landroni** [comment]
I pulled master, but I don't think this feature is working here. Is it on a branch?

**Comment by hasufell** [comment]
https://github.com/nicklan/pnmixer/blob/master/src/callbacks.c#L386 it is on master and it should work

**Comment by elboulangero** [comment]
This commit changes some UI files as well. If you just compile PNMixer and run it, it's not enough, since PNMixer will load UI files that are already installed on your machine (`/usr/local/share/pnmixer/ui/` for me) instead of the new UI files from source (in `data/` directory). So you need to install PNMixer, or at least copy manually the UI files.
This being said, I think it's also something we should improve, each time I touch the UI files it's a real pain.

**Comment by hasufell** [comment]
That is weird. I do not have to reinstall them

**Comment by elboulangero** [comment]
Maybe it's a distro thing. I'm with Debian, what about you ?

**Comment by hasufell** [comment]
Ah, I know why... I install it into `/usr/share/pnmixer/ui` but the default installation when you run configure is `/usr/local/share/pnmixer/ui`. I think it should work if you set `-DPACKAGE_DATA_DIR=...` to something invalid, because then `get_ui_file()` will use the fallback of the project dir.

**Comment by elboulangero** [comment]
Yep. By the way, instead of using a kind of hard-coded `PACKAGE_DATA_DIR`, Glib provides `g_get_system_data_dirs ()`, it's probably a better way to look for ui files in standard locations...
Anyway, I don't know how other software handle that. Maybe we should just look for local UI file at first, then in `PACKAGE_DATA_DIR` ?

**Comment by hasufell** [comment]
> Yep. By the way, instead of using a kind of hard-coded PACKAGE_DATA_DIR, Glib provides g_get_system_data_dirs (), it's probably a better way to look for ui files in standard locations...

I don't like `g_get_system_data_dirs()`, because it basically just reads the env variable `XDG_DATA_DIRS`. That will not allow to install pnmixer in non-standard locations.

> Maybe we should just look for local UI file at first, then in PACKAGE_DATA_DIR ?

That sounds reasonable.

**Comment by hasufell** [comment]
b43a6bc2bf0c06135c7c5a9e704d912752eeb1cc

**Comment by landroni** [comment]
Indeed, I was trying out pnmixer from the source dir. I've now installed master, and the ESC/Enter feature works as expected.

**Comment by elboulangero** [comment]
@hasufell :+1:
